datasources:
  - name: prometheus
    type: prometheus
    typeName: Prometheus
    typeLogoUrl: /public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    access: proxy
    url: http://host.docker.internal:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo
